version: '3.4'

services:
  godev:
    build:
      context: .
      dockerfile: ./dockerfiles/godev.dockerfile
    image: localhost/alsad/smoke-test/godev:1.9-alpine
    working_dir: /go/src/github.com/ALSAD-project/smoke-test
    volumes:
      - .:/go/src/github.com/ALSAD-project/smoke-test

  randfeeder:
    image: alsad/smoke-test-randfeeder:git-edc32f7
    ports:
      - 6010
    environment:
      RF_DATA_VARIANCE: 10
      RF_NOISE_MAGNITUDE: 20
      RF_NOISE_VARIANCE: 50

